--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-1.pgdg120+1)
-- Dumped by pg_dump version 15.8 (Debian 15.8-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    date_of_creation timestamp(6) without time zone,
    description character varying(255),
    in_sale boolean,
    name character varying(255),
    quantity integer NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sku (
    id bigint NOT NULL,
    available boolean,
    color character varying(255),
    product_id bigint
);


ALTER TABLE public.sku OWNER TO postgres;

--
-- Name: sku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, date_of_creation, description, in_sale, name, quantity) FROM stdin;
20	2024-10-16 00:00:00	Tonic water with a hint of lemon	t	Schweppes	11
15	2024-10-11 06:50:00	Sports drink with electrolytes	t	Gatorade	9
16	2024-10-10 11:35:00	Flavoured water with vitamins	f	Vitamin Water	2
8	2024-10-19 11:30:00	Citrus-flavoured soft drink	f	Mountain Dew	0
12	2024-10-21 09:05:00	Energy drink with a bold flavour	t	Monster	17
5	2024-10-18 10:00:00	Classic cola soft drink	f	 Coca-Cola	5
7	2024-10-14 09:20:00	Cola soft drink with a sweet taste	t	Pepsi	25
13	2024-10-13 08:30:00	Orange juice 100% natural	f	Tropicana	1
14	2024-10-12 07:15:00	Lemon-flavoured iced tea	t	Lipton Iced Tea	14
9	2024-10-20 16:45:00	Unique blend of 23 flavours	t	Dr Pepper	18
19	2024-10-08 15:25:00	Italian sparkling water	f	San Pellegrino	4
6	2024-10-16 12:15:00	Orange-flavoured soft drink	t	Fanta	12
11	2024-10-20 16:45:00	Energy drink with caffeine and taurine	t	Red Bull	22
3	2024-10-05 08:00:00	Antioxidant-infused beverage	f	Bai	15
10	2024-10-18 14:00:00	Lemon-lime soft drink	f	7 Up	3
4	2024-10-04 07:30:00	Sparkling water with natural flavours	f	LaCroix	8
17	2024-10-15 10:10:00	Sweetened lemon iced tea	t	Nestea	30
18	2024-10-09 09:40:00	Sparkling mineral water	t	Perrier	20
2	2024-10-15 03:09:03	Lime-flavoured soft drink	t	Sprite	20
42	2023-09-30 03:00:00	Updated description	f	Updated Product	30
\.


--
-- Data for Name: sku; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sku (id, available, color, product_id) FROM stdin;
4	t	Red	2
61	t	Green	2
20	f	Updated Color	7
5	f	Black	2
6	t	White	3
7	t	Purple	3
8	f	Orange	3
9	t	Pink	4
10	t	Gray	4
11	f	Brown	4
12	t	Beige	5
13	t	Cyan	5
14	f	Magenta	5
15	t	Lime	6
16	t	Navy	6
17	f	Teal	6
18	t	Coral	7
19	t	Maroon	7
21	t	Gold	8
22	t	Silver	8
23	f	Bronze	8
24	t	Lavender	9
25	t	Mint	9
26	f	Peach	9
27	t	Rose	10
28	t	Ivory	10
29	f	Cream	10
30	t	Emerald	11
31	t	Sapphire	11
32	f	Ruby	11
33	t	Indigo	12
34	t	Violet	12
35	f	Azure	12
36	t	Burgundy	13
37	t	Charcoal	13
38	f	Copper	13
39	t	Salmon	14
40	t	Honey	14
41	f	Amber	14
42	t	Apricot	15
43	t	Lavender	15
44	f	Fuchsia	15
45	t	Periwinkle	16
46	t	Wheat	16
47	f	Cobalt	16
48	t	Onyx	17
49	t	Quartz	17
50	f	Topaz	17
51	t	Turquoise	18
52	t	Jade	18
53	f	Aquamarine	18
54	t	Pewter	19
55	t	Steel	19
56	f	Slate	19
57	t	Copper	20
58	t	Zinc	20
59	f	Nickel	20
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 42, true);


--
-- Name: sku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sku_id_seq', 61, true);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: sku sku_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT sku_pkey PRIMARY KEY (id);


--
-- Name: sku fkovd96qvc9da3k94gf0j822p3o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT fkovd96qvc9da3k94gf0j822p3o FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- PostgreSQL database dump complete
--

